### ISSUE TITLE
Drone Network doesn't work properly

### ISSUE THREAD

**Issue by JollyChristopher** [Red-dog95/scotts-mods#2]
**Issue Description:**

1. From this forum post: https://mods.factorio.com/mod/Scotts_Logistics/discussion/5c3b861c7132ab000cc67293. Basically, the recipe for the drone port is not available.
1. Drone chests do not hook up to drone networks (drone ports) and instead continue to flash and not provide materials to drones.

**Version Found:**
0.16.5
**Possible Solutions:**
for 1: You need to only add the recipe to the technology for simple-logistics-system (or other).
for 2: I have no idea offhand. Seems like what is happening is that the passive providers still want to connect to a regular roboport instead of a drone port.

**Comment by Red-dog95** [comment]
Issue has been resolved! thanks for the comment, sorry it took so long to update.

**Comment by JollyChristopher** [comment]
No problem, that is actually a much faster update than expected.
However, tried to run the new update and got this:
![scotts_logistics_error](https://user-images.githubusercontent.com/6564772/51161643-0c9f7700-1848-11e9-8fe8-8a759fb93f35.PNG)

**Comment by Red-dog95** [comment]
Well shoot my bad.

**Comment by JollyChristopher** [comment]
Mod now loads, but as for "Drone chests do not hook up to drone networks (drone ports) and instead continue to flash and not provide materials to drones.", here is a screenshot:
![scotts_logistics_drone](https://user-images.githubusercontent.com/6564772/51204387-5cb62200-18b8-11e9-9880-09eb0541fff8.PNG)

By scrolling over the drone port, it seems the supply area is 0x0 so the chests cannot connect to the drone port.

EDIT: This does seem to be the case, as I increased to "4" and the chests were able to have items taken from them from 2 blocks away from the port. Basically, you need some positive number, otherwise you have no way of having the drones pick up items to make blueprints.

**Comment by Red-dog95** [comment]
thanks for the update, I didn't want the drone ports to be able to deal with logistics robots later in the game, but I guess it's required to allow even the construction robots. Anyway I've updated it with a small radius. You've been pretty helpful, and I apologize from hindering your factorio experience. If you'd like something added to this mod or one of the other ones I'm working on please let me know. I'd happily add it as a thank you.

**Comment by JollyChristopher** [comment]
Ohh don't worry about it. You've had the mod out for what, 2 weeks now? The fact that it works so well up to this point is great! I just want to make sure you get all the info you need to make a cool mod and giving you bug reports is one of the ways I can do that.
As for other suggestions, not sure right now, If I think of something I can add it to the forums.

I'll close this once we've got the drones figured out here. I think the radius will need to be more than 2, since 4 made it only 2 blocks away from the roboport, so I suspect 2 would make it "only if the chests are literally inside the roboport" which wouldn't work.
